export const users = [
  {
    id: 1,
    name: "Faruq",
    username: "faruq01",
    email: "faruq@gmail.com",
    phone: "7676041124",
    gender: "male",
    age: 23,
    role: "sub-agent",
    status: true,
    entityId: "ENT001",
    parentId: "ADMIN001",
    profileImage: "",
  },
  {
    id: 2,
    name: "Rizwan Pathan",
    username: "rizwanp",
    email: "rizwan@gmail.com",
    phone: "963881369",
    gender: "other",
    age: 28,
    role: "sub-agent",
    status: true,
    entityId: "ENT002",
    parentId: "ADMIN001",
    profileImage: "",
  },
];
